# CircleCI configuration file
version: 2.1

orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Setup custom environment variables"
          command: echo 'export \n
            MY_ENV_VAR="FOO"\n
            envkey_API_KEY:${{ secrets.API_KEY }} \n
            envkey_CLIENT_URL:${{ secrets.CLIENT_URL }} \n
            envkey_CLOUDNARY_API_KEY:${{ secrets.CLOUDNARY_API_KEY }} \n
            envkey_CLOUDNARY_API_SECRET:${{ secrets.CLOUDNARY_API_SECRET }} \n
            envkey_CLOUDNARY_NAME:${{ secrets.CLOUDNARY_NAME }} \n
            envkey_CONNECTION_STRING:${{ secrets.CONNECTION_STRING }} \n
            envkey_DB_PASSWORD:${{ secrets.DB_PASSWORD }} \n
            envkey_DB_USERNAME:${{ secrets.DB_USERNAME }} \n
            envkey_EMAIL_PASSWORD_PROD:${{ secrets.EMAIL_PASSWORD_PROD }} \n
            envkey_EMAIL_USERNAME_PROD:${{ secrets.EMAIL_USERNAME_PROD }} \n
            envkey_JWT_SECRET:${{ secrets.JWT_SECRET }} \n
            envkey_OAUTH_CLIENTID:${{ secrets.OAUTH_CLIENTID }} \n
            envkey_OAUTH_CLIENT_SECRET:${{ secrets.OAUTH_CLIENT_SECRET }} \n
            envkey_OAUTH_REFRESH_TOKEN:${{ secrets.OAUTH_REFRESH_TOKEN }} \n
            envkey_REDIRECT_URL:${{ secrets.REDIRECT_URL }} \n
            envkey_NODE_ENV:${{ secrets.NODE_ENV }} \n' >> "$BASH_ENV"
      - run:
          command: npm install
          name: Install dependencies
      - run:
          command: npm run test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  # Name of workflow
  test:
    # List of jobs that will run
    jobs:
      - build_and_test
